title: using-pip-on-raspberry-pi
hero_image: images/banner.png
description: Learn about pip for your Pi
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, art, humour, space, photography, outdoors, music, games
technologies: electronic-components, sense-hat, html-css-javascript, scratch, python
site_areas: coderdojo
hardware: electronic-components, sense-hat
software: html-css-javascript, scratch, python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: What is pip?
- title: Upgrading pip
- title: Using pip
- title: What next?