title: Using pip on Raspberry Pi
hero_image: images/banner.png
description: Learn about installing Python software on your Pi with pip
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: What is pip?
- title: Upgrading pip
- title: Using pip
- title: What next?
