---
title: Použití pip na Raspberry Pi
hero_image: images/banner.png
description: Zjisti více o instalaci Python softwaru pomocí pip do tvého Raspberry Pi
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - title: Úvod
  - title: Co budeš potřebovat
  - title: Co je pip?
  - title: Aktualizace pip
    completion:
      - engaged
  - title: Použití pip
    completion:
      - internal
    completion:
      - external